services:
  app:
    image: 'newphp-site'
    volumes:
      - '.:/var/www'
    build: .
    networks:
      - newphp
    depends_on:
      - db

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
        - "1337:80"
    volumes:
        - ./:/var/www
        - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - newphp
    depends_on:
      - db

  db:
    image: mariadb:10.10.3
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
    volumes:
      - database:/var/lib/mysql
      # - ./db/db1.sql:/docker-entrypoint-initdb.d/db1.sql
      # - ./db/inoa.sql:/docker-entrypoint-initdb.d/inoa.sql
    networks:
      - newphp

networks:
  newphp:
    driver: bridge

volumes:
  database:
