services:
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    env_file: .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
      - UPLOAD_LIMIT=999999999
    ports:
      - '1338:80'
    networks:
      - newphp

networks:
  newphp:
    driver: bridge

volumes:
  database:
