version: '3.7'

services:
  app:
    image: 'newphp-site'
    volumes:
      - '.:/var/www'
    build: .
    networks:
      - newphp
    depends_on:
      - db

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
        - "1337:80"
    volumes:
        - ./:/var/www
        - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - newphp
    depends_on:
      - db

  db:
    image: mariadb:10.10.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'f0767272_db'
      MYSQL_ROOT_PASSWORD: 'imuwukbema'
      MYSQL_PASSWORD: 'imuwukbema'
      MYSQL_USER: 'f0767272'
    volumes:
      - database:/var/lib/mysql
    networks:
      - newphp

networks:
  newphp:
    driver: bridge

volumes:
  database:
